[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/EddiazOS/LC_data_review/blob/main/05_Analisis_Reproducible/notebooks/02_nivel_2_variabilidad_espacial.ipynb)

# Notebook 02: Nivel 2 — Variabilidad Espacial, Contrastes Microambientales y Pruebas de Hipótesis
### Subsección 3.2 del Manuscrito: Diseño Experimental Incompleto, Árbol de Decisión a Priori y Control FDR
**Proyecto LC-GC / Indoor Dust — Universidad de Cartagena & Universidad de Amberes**

---

### Objetivos Metodológicos y Analíticos:
1. **Diseño Experimental y Diagnóstico de Censura:** Documentar la matriz de diseño factorial incompleto con ceros estructurales ($3 \times 3$, 4 celdas con $n=0$, 5 celdas observadas) y clasificar los 35 compuestos según su nivel de censura analítica ($\%\text{ND}$).
2. **Árbol de Decisión Algorítmico *a Priori*:** Implementar el diagnóstico formal de supuestos sobre los **residuos del modelo lineal en $\log_{10}$** (Shapiro-Wilk) y homogeneidad de varianza (Levene centrado en la mediana) para asignar objetivamente cada compuesto a ANOVA clásico, ANOVA Welch o Kruskal-Wallis antes de evaluar significancias.
3. **Contraste Omnibus Microambiental y Post-hoc:** Aplicar la prueba principal asignada por compuesto entre microambientes (Car vs House vs Office), seguida de comparaciones post-hoc (Tukey-Kramer para ANOVA; Dunn para Kruskal-Wallis) y control de multiplicidad mediante **False Discovery Rate (FDR, Benjamini-Hochberg)**.
4. **Análisis de Sensibilidad Metodológica:** Comparar sistemáticamente las decisiones inferenciales de ANOVA vs Kruskal-Wallis para demostrar la robustez e invariancia de las conclusiones científicas.
5. **Sub-diseños Ortogonales y Gradientes Geográficos:** Aislar comparaciones controladas libres de sesgo de confusión: microambiente puro dentro de Medellín ($N=25$), y gradientes de ciudades en viviendas (Bogotá vs Medellín, $N=24$) y vehículos (Cartagena vs Medellín, $N=12$).
6. **Inspección Visual y Publicación:** Mantener la suite diagnóstica de densidades KDE (Panel principal 2×3 y 4 Anexos 3×3) y generar las Figuras oficiales 2 y 3 a 300 DPI.

In [1]:
# Celda 1: Configuración de Entorno (Google Colab / Local) y Pre-requisitos
import os
import sys

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    print("🚀 Entorno Google Colab detectado.")
    if not os.path.exists('LC_data_review'):
        !git clone https://github.com/EddiazOS/LC_data_review.git
    if os.path.exists('LC_data_review/05_Analisis_Reproducible/datos_curados'):
        DATA_DIR = 'LC_data_review/05_Analisis_Reproducible/datos_curados'
        OUT_TABLES = 'LC_data_review/05_Analisis_Reproducible/outputs/tablas'
        OUT_FIGS = 'LC_data_review/05_Analisis_Reproducible/outputs/figuras'
    else:
        DATA_DIR = '../datos_curados'
        OUT_TABLES = '../outputs/tablas'
        OUT_FIGS = '../outputs/figuras'
    !pip install -q scikit-posthocs statsmodels
else:
    print("💻 Entorno Local detectado.")
    DATA_DIR = '../datos_curados' if os.path.exists('../datos_curados') else '05_Analisis_Reproducible/datos_curados'
    OUT_TABLES = '../outputs/tablas' if os.path.exists('../outputs/tablas') else '05_Analisis_Reproducible/outputs/tablas'
    OUT_FIGS = '../outputs/figuras' if os.path.exists('../outputs/figuras') else '05_Analisis_Reproducible/outputs/figuras'

os.makedirs(OUT_TABLES, exist_ok=True)
os.makedirs(OUT_FIGS, exist_ok=True)
print(f"Directorio de datos activo: {DATA_DIR}")
print(f"Directorio de tablas:       {OUT_TABLES}")
print(f"Directorio de figuras:      {OUT_FIGS}")

import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multitest import multipletests
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import scikit_posthocs as sp
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['font.size'] = 10
plt.rcParams['axes.linewidth'] = 1.0
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['savefig.bbox'] = 'tight'

print("Librerías importadas y configuradas correctamente.")

💻 Entorno Local detectado.
Directorio de datos activo: ../datos_curados
Directorio de tablas:       ../outputs/tablas
Directorio de figuras:      ../outputs/figuras

Librerías importadas y configuradas correctamente.

In [2]:
# Celda 2: Carga de Datos Curados y Balance de Masa Acumulado Muestra a Muestra
df_muestras = pd.read_csv(os.path.join(DATA_DIR, 'muestras_metadata.csv'))
df_compuestos = pd.read_csv(os.path.join(DATA_DIR, 'compuestos_metadata.csv'))
df_conc = pd.read_csv(os.path.join(DATA_DIR, 'concentraciones_ng_g.csv'))
df_det = pd.read_csv(os.path.join(DATA_DIR, 'estado_deteccion.csv'))
df_loq = pd.read_csv(os.path.join(DATA_DIR, 'limites_cuantificacion.csv'))

acronyms = df_compuestos['acronym'].tolist()
fam_map = dict(zip(df_compuestos['acronym'], df_compuestos['family']))

ap_cols = [c for c in acronyms if fam_map[c] == 'APs']
pfr_cols = [c for c in acronyms if fam_map[c] == 'PFRs']
ph_cols = [c for c in acronyms if fam_map[c] == 'PHs']

# Balance de masa estricto muestra a muestra (axis=1)
df_muestras['Sum_APs'] = df_conc[ap_cols].sum(axis=1)
df_muestras['Sum_PFRs'] = df_conc[pfr_cols].sum(axis=1)
df_muestras['Sum_PHs'] = df_conc[ph_cols].sum(axis=1)
df_muestras['Sum_Total'] = df_muestras['Sum_APs'] + df_muestras['Sum_PFRs'] + df_muestras['Sum_PHs']

# Variable combinada de celda ambiental (ciudad x microambiente)
df_muestras['cell'] = df_muestras['city'] + '_' + df_muestras['microenvironment']

print(f"Cargadas {len(df_muestras)} muestras ambientales con {len(acronyms)} compuestos diana.")
print("Distribución de celdas observadas en el diseño:")
print(df_muestras['cell'].value_counts())

Cargadas 44 muestras ambientales con 35 compuestos diana.
Distribución de celdas observadas en el diseño:
cell
Bogota_House       14
Medellin_House     10
Medellin_Office     8
Medellin_Car        7
Cartagena_Car       5
Name: count, dtype: int64

# 1. Marco Metodológico: Diseño Experimental, Filtro de Censura y Diagnóstico de Residuos

## 1.1 Naturaleza del Diseño: Factorial Incompleto con Ceros Estructurales
El diseño experimental contempla dos factores categóricos: **Ciudad** ($I = 3$: Bogotá, Medellín, Cartagena) y **Microambiente** ($J = 3$: Car, House, Office). En un diseño factorial cruzado estándar, existirían $3 \times 3 = 9$ celdas de tratamiento. Sin embargo, en el presente estudio cuatro celdas carecen de muestras físicas ($n=0$):
- **Bogotá ($n=14$):** Únicamente viviendas residenciales (0 autos, 0 oficinas).
- **Cartagena ($n=5$):** Únicamente vehículos particulares (0 casas, 0 oficinas).
- **Medellín ($n=25$):** Distribución balanceada en los tres microambientes (10 casas, 7 autos, 8 oficinas).

Matemáticamente, un modelo de dos vías con interacción completa `log(conc) ~ ciudad * microambiente` genera una **matriz de diseño singular de rango deficiente**, pues los grados de libertad de la interacción no son estimables. Para abordar este diseño incompleto de forma rigurosa conforme a la literatura (*Searle, 1987; Milliken & Johnson, 2009*):
1. Se formula el **Modelo de 5 Celdas Ambientales (*Cell-Means Model*)**:
   $$\log_{10}(Y_{ik}) = \mu_k + \epsilon_{ik}, \quad k = 1, \dots, 5; \quad i = 1, \dots, n_k$$
   donde $\mu_k$ representa la media de cada celda observada y $\epsilon_{ik}$ el error aleatorio intra-celda ($df_{\text{error}} = 44 - 5 = 39$).
2. Sobre los **residuos conjuntos** de este modelo ($e_{ik} = \log_{10}(Y_{ik}) - \hat{\mu}_k$) se evalúan los supuestos paramétricos con el máximo tamaño muestral ($N = 44$).

---

## 1.2 Árbol de Decisión Algorítmico *a Priori*
Para prevenir el sesgo de selección metodológica (*p-hacking*), se establece un protocolo estricto de decisión previa aplicado uniformemente a los 35 compuestos y 4 sumatorias familiares:

1. **Regla 1 (Filtro de Censura Analítica):** Si un compuesto presenta una frecuencia de no detección $\text{ND} > 50\%$ (equivalente a $\text{DF} < 50\%$), los modelos lineales no son apropiados debido a la concentración artificial de empates en el umbral sustituto. Se asigna a la **Rama 4 (Estadística Descriptiva y Proporciones)**.
2. **Regla 2 (Log-Transformación):** Para los compuestos elegibles ($\text{DF} \ge 50\%$), se aplica la transformación $\log_{10}(X + 1)$ para estabilizar la varianza y mitigar la asimetría positiva severa.
3. **Regla 3 (Diagnóstico Formal de Residuos):** Se ajusta el modelo lineal sobre $\log_{10}$ y se evalúa:
   - **Normalidad de Residuos:** Prueba de Shapiro-Wilk sobre los residuos agrupados ($e_{ik}$).
   - **Homocedasticidad:** Prueba de Levene centrada en la mediana (*Brown-Forsythe*) entre las celdas ambientales.
4. **Regla 4 (Bifurcación Metodológica Objetiva):**
   - **Rama 1 (ANOVA Clásico):** Si $p_{\text{Shapiro}} \ge 0.05$ y $p_{\text{Levene}} \ge 0.05$ $\rightarrow$ ANOVA $F$-test (Tipo II) con comparaciones post-hoc de **Tukey-Kramer** (diseñado para tamaños muestrales desiguales).
   - **Rama 2 (ANOVA Robusto / Welch):** Si $p_{\text{Shapiro}} \ge 0.05$ pero $p_{\text{Levene}} < 0.05$ $\rightarrow$ ANOVA de Welch con corrección de heterocedasticidad y post-hoc de **Games-Howell**.
   - **Rama 3 (Kruskal-Wallis):** Si $p_{\text{Shapiro}} < 0.05$ (residuos no normales tras transformación logarítmica) $\rightarrow$ Prueba no paramétrica de **Kruskal-Wallis** con post-hoc de **Dunn**.
5. **Regla 5 (Control de Multiplicidad Global):** Todos los $p$-valores omnibus y contrastes de hipótesis se ajustan mediante el procedimiento de **False Discovery Rate (FDR, Benjamini-Hochberg)**.

In [3]:
# Celda 3: Matriz de Diseño, Diagnóstico de Residuos y Árbol de Decisión a Priori
print("=== 1. MATRIZ DE DISEÑO Y FILTRO DE CENSURA ANALÍTICA (% ND) ===\n")

# A. Tabla cruzada de diseño experimental
ct_design = pd.crosstab(df_muestras['city'], df_muestras['microenvironment'], margins=True)
print("Tabla Cruzada de Muestras (Ciudad x Microambiente):")
print(ct_design)

# B. Clasificación de Censura para los 35 compuestos
cens_records = []
for acr in acronyms:
    n_det = (df_det[acr] == 1).sum()
    df_pct = (n_det / len(df_det)) * 100.0
    nd_pct = 100.0 - df_pct
    cens_records.append({
        'Compound': acr,
        'Family': fam_map[acr],
        'Detections': n_det,
        'Total_Samples': len(df_det),
        'DF_pct': round(df_pct, 2),
        'ND_pct': round(nd_pct, 2),
        'Eligible_Model': 'Elegible (DF >= 50%)' if df_pct >= 50.0 else 'Excluido (ND > 50%)',
        'Approach': 'Modelado Log10 & Residuos' if df_pct >= 50.0 else 'Descriptivo / Proporciones'
    })

df_cens = pd.DataFrame(cens_records)
path_cens = os.path.join(OUT_TABLES, 'tabla_2_15_matriz_diseno_y_censura.csv')
df_cens.to_csv(path_cens, index=False)
print(f"\nTabla de censura analítica exportada a: {path_cens}")
print(f" • Compuestos elegibles para modelado (DF >= 50%): {(df_cens['DF_pct'] >= 50).sum()} / 35")
print(f" • Compuestos con alta censura (ND > 50%):           {(df_cens['DF_pct'] < 50).sum()} / 35: {df_cens[df_cens['DF_pct'] < 50]['Compound'].tolist()}")

# C. Diagnóstico Formal sobre los Residuos del Modelo en log10
print("\n=== 2. DIAGNÓSTICO FORMAL DE RESIDUOS (SHAPIRO-WILK) Y HOMOCEDASTICIDAD (LEVENE) ===\n")

all_vars = ['Sum_Total', 'Sum_APs', 'Sum_PFRs', 'Sum_PHs'] + acronyms
tree_records = []

for var in all_vars:
    is_sum = var.startswith('Sum_')
    fam = 'Global' if is_sum else fam_map[var]
    
    if not is_sum:
        df_pct = (df_det[var] == 1).mean() * 100.0
        if df_pct < 50.0:
            tree_records.append({
                'Variable': var, 'Family': fam, 'DF_pct': round(df_pct, 2), 'ND_pct': round(100.0-df_pct, 2),
                'Shapiro_Resid_W': np.nan, 'Shapiro_Resid_p': np.nan, 'Norm_Resid': 'N/A (ND > 50%)',
                'Levene_Cell_stat': np.nan, 'Levene_Cell_p': np.nan, 'Homoced_Cell': 'N/A (ND > 50%)',
                'Method_Branch': 'Rama 4: Descriptivo / Censurado',
                'Primary_Test': 'Estadística Descriptiva & Proporciones',
                'Post_Hoc_Test': 'N/A'
            })
            continue
    else:
        df_pct = 100.0
        
    vals = df_muestras[var].values if is_sum else df_conc[var].values
    log_vals = np.log10(vals + 1.0)
    
    df_t = pd.DataFrame({'log_y': log_vals, 'cell': df_muestras['cell'], 'micro': df_muestras['microenvironment']})
    m = ols('log_y ~ C(cell)', data=df_t).fit()
    
    sw_w, sw_p = stats.shapiro(m.resid)
    cell_groups = [g['log_y'].values for _, g in df_t.groupby('cell')]
    lev_stat, lev_p = stats.levene(*cell_groups, center='median')
    
    norm_ok = sw_p >= 0.05
    homo_ok = lev_p >= 0.05
    
    if norm_ok and homo_ok:
        branch = 'Rama 1: ANOVA Clásico'
        prim_test = 'ANOVA F-test (Tipo II)'
        post_test = 'Tukey-Kramer'
    elif norm_ok and not homo_ok:
        branch = 'Rama 2: ANOVA Welch / Robusto'
        prim_test = 'ANOVA Welch (Heterocedástico)'
        post_test = 'Games-Howell'
    else:
        branch = 'Rama 3: Kruskal-Wallis'
        prim_test = 'Kruskal-Wallis (Residuos no normales)'
        post_test = 'Dunn (Ajuste FDR)'
        
    tree_records.append({
        'Variable': var, 'Family': fam, 'DF_pct': round(df_pct, 2), 'ND_pct': round(100.0-df_pct, 2),
        'Shapiro_Resid_W': round(sw_w, 4), 'Shapiro_Resid_p': sw_p,
        'Norm_Resid': 'Normal (p >= 0.05)' if norm_ok else 'No Normal (p < 0.05)',
        'Levene_Cell_stat': round(lev_stat, 4), 'Levene_Cell_p': lev_p,
        'Homoced_Cell': 'Homocedástico (p >= 0.05)' if homo_ok else 'Heterocedástico (p < 0.05)',
        'Method_Branch': branch,
        'Primary_Test': prim_test,
        'Post_Hoc_Test': post_test
    })

df_tree = pd.DataFrame(tree_records)
path_tree = os.path.join(OUT_TABLES, 'tabla_2_16_diagnostico_residuos_y_clasificacion.csv')
df_tree.to_csv(path_tree, index=False)
print(f"Tabla diagnóstica de clasificación a priori exportada a: {path_tree}\n")

print("=== DISTRIBUCIÓN DE VARIABLES POR RAMA METODOLÓGICA (Total = 39) ===")
print(df_tree['Method_Branch'].value_counts())
display(df_tree[['Variable', 'Family', 'DF_pct', 'Norm_Resid', 'Homoced_Cell', 'Method_Branch', 'Primary_Test']])

=== 1. MATRIZ DE DISEÑO Y FILTRO DE CENSURA ANALÍTICA (% ND) ===

Tabla Cruzada de Muestras (Ciudad x Microambiente):
microenvironment  Car  House  Office  All
city
Bogota              0     14       0   14
Cartagena           5      0       0    5
Medellin            7     10       8   25
All                12     24       8   44

Tabla de censura analítica exportada a: ../outputs/tablas/tabla_2_15_matriz_diseno_y_censura.csv
 • Compuestos elegibles para modelado (DF >= 50%): 30 / 35
 • Compuestos con alta censura (ND > 50%):           5 / 35: ['DIBA', 'TDBPP', 'TDCIPP', 'TEP', 'V6']

=== 2. DIAGNÓSTICO FORMAL DE RESIDUOS (SHAPIRO-WILK) Y HOMOCEDASTICIDAD (LEVENE) ===

Tabla diagnóstica de clasificación a priori exportada a: ../outputs/tablas/tabla_2_16_diagnostico_residuos_y_clasificacion.csv

=== DISTRIBUCIÓN DE VARIABLES POR RAMA METODOLÓGICA (Total = 39) ===
Method_Branch
Rama 1: ANOVA Clásico              18
Rama 3: Kruskal-Wallis             14
Rama 4: Descriptivo / Censurado     5
Rama 2: ANOVA Welch / Robusto       2
Name: count, dtype: int64

,Variable,Family,DF_pct,Norm_Resid,Homoced_Cell,Method_Branch,Primary_Test
0,Sum_Total,Global,100.00,No Normal (p < 0.05),Heterocedástico (p < 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
1,Sum_APs,Global,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
2,Sum_PFRs,Global,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
3,Sum_PHs,Global,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
4,ATBC,APs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
5,ATEC,APs,88.64,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
6,BTHC,APs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
7,CDPHP,APs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
8,DBS,APs,70.45,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
9,DEHA,APs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
10,DIBA,APs,34.09,N/A (ND > 50%),N/A (ND > 50%),Rama 4: Descriptivo / Censurado,Estadística Descriptiva & Proporciones
11,DINCH,APs,75.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
12,THTM,APs,95.45,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
13,TOTM,APs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
14,BDP,PFRs,93.18,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
15,EHDPHP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
16,RDP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
17,TBOEP,PFRs,97.73,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
18,TBP1,PFRs,90.91,Normal (p >= 0.05),Heterocedástico (p < 0.05),Rama 2: ANOVA Welch / Robusto,ANOVA Welch (Heterocedástico)
19,TBP2,PFRs,93.18,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
20,TBuPhP,PFRs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
21,TCEP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
22,TCIPP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
23,TDBPP,PFRs,11.36,N/A (ND > 50%),N/A (ND > 50%),Rama 4: Descriptivo / Censurado,Estadística Descriptiva & Proporciones
24,TDCIPP,PFRs,34.09,N/A (ND > 50%),N/A (ND > 50%),Rama 4: Descriptivo / Censurado,Estadística Descriptiva & Proporciones
25,TEHP,PFRs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
26,TEP,PFRs,31.82,N/A (ND > 50%),N/A (ND > 50%),Rama 4: Descriptivo / Censurado,Estadística Descriptiva & Proporciones
27,TPhP,PFRs,97.73,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
28,TpTP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
29,V6,PFRs,38.64,N/A (ND > 50%),N/A (ND > 50%),Rama 4: Descriptivo / Censurado,Estadística Descriptiva & Proporciones
30,iDPP,PFRs,100.00,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
31,BBzP,PHs,100.00,Normal (p >= 0.05),Heterocedástico (p < 0.05),Rama 2: ANOVA Welch / Robusto,ANOVA Welch (Heterocedástico)
32,DEP,PHs,95.45,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
33,DIDP,PHs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
34,DINP,PHs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
35,DMP,PHs,95.45,Normal (p >= 0.05),Homocedástico (p >= 0.05),Rama 1: ANOVA Clásico,ANOVA F-test (Tipo II)
36,DPP,PHs,75.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
37,DiBP,PHs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)
38,DnBP,PHs,100.00,No Normal (p < 0.05),Homocedástico (p >= 0.05),Rama 3: Kruskal-Wallis,Kruskal-Wallis (Residuos no normales)

## 1.3 Inspección Visual de Distribuciones KDE y Diagnóstico de Log-Normalidad (Figuras S3 y S4)

Para complementar el diagnóstico numérico de Shapiro-Wilk y Levene, se implementa una evaluación visual completa basada en **Estimación de Densidad por Kernel (KDE)** en dos niveles:
1. **Figura S3 (Panel Principal 2×3)**: Matriz balanceada de las tres familias químicas (APs, PFRs, PHs) contrastando la distribución de concentraciones crudas ($	ext{ng/g}$) en la fila superior frente a la transformación $\log_{10}(	ext{ng/g})$ en la fila inferior.
2. **Figuras S4a–d (Suite de Anexos 3×3)**: Cuatro paneles de $3 	imes 3$ cuadrantes que desglosan individualmente los 35 compuestos diana ($9 + 9 + 9 + 8 = 35$ compuestos, ocupando el puesto restante con un cuadro metodológico integrado). En cada cuadrante se superpone la curva KDE empírica con la campana gaussiana teórica $\mathcal{N}(\mu, \sigma)$ ajustada a los datos, acompañada de los estadísticos diagnósticos clave ($	ext{Skewness}_{	ext{crudo}}$, $	ext{Skewness}_{\log}$, $p$-valor de Shapiro-Wilk, Mediana e IQR).

In [4]:
# Celda 3b: Generación de Figuras de Distribuciones KDE (Panel 2x3 y Suite 3x3 de Anexos)
print("=== GENERANDO FIGURA S3 (PANEL 2x3) Y FIGURAS S4a-d (SUITE 3x3 ANEXOS) ===")

colores_fam = {
    'APs': '#2E86AB',
    'PFRs': '#D9534F',
    'PHs': '#5CB85C'
}

# -------------------------------------------------------------------------
# 1. FIGURA S3: PANEL BALANCEADO 2x3 (Familias en Columnas x Escalas en Filas)
# -------------------------------------------------------------------------
fig_s3, axes_s3 = plt.subplots(2, 3, figsize=(16, 10))
familias = ['APs', 'PFRs', 'PHs']
fam_titulos = {
    'APs': 'Alternative Plasticizers (APs)',
    'PFRs': 'Organophosphate Flame Retardants (PFRs)',
    'PHs': 'Phthalates (PHs)'
}

for col_idx, fam in enumerate(familias):
    col_sum = f'Sum_{fam}'
    data_cruda = df_muestras[col_sum].values
    data_log = np.log10(data_cruda + 1.0)
    color = colores_fam[fam]

    # Fila 0: Escala Cruda (ng/g)
    ax_cruda = axes_s3[0, col_idx]
    sns.kdeplot(data_cruda, ax=ax_cruda, color=color, fill=True, alpha=0.35, linewidth=2.2, bw_adjust=0.8)
    rug_cruda = data_cruda[data_cruda < np.percentile(data_cruda, 95)]
    ax_cruda.plot(rug_cruda, np.zeros_like(rug_cruda), '|', color=color, markersize=8, alpha=0.6)
    
    skew_cruda = stats.skew(data_cruda)
    med_cruda = np.median(data_cruda)
    ax_cruda.axvline(med_cruda, color='black', linestyle='--', linewidth=1.5, label=f'Mediana: {med_cruda:,.0f} ng/g')
    ax_cruda.set_title(f"{fam_titulos[fam]}\nEscala Cruda [Skewness = {skew_cruda:.2f}]", fontsize=11, fontweight='bold', pad=10)
    ax_cruda.set_xlabel('Concentración (ng/g)', fontsize=10, fontweight='bold')
    ax_cruda.set_ylabel('Densidad de Probabilidad' if col_idx == 0 else '', fontsize=10, fontweight='bold')
    ax_cruda.legend(loc='upper right', frameon=True, fontsize=9)
    ax_cruda.grid(True, linestyle=':', alpha=0.4)
    ax_cruda.ticklabel_format(style='scientific', scilimits=(0, 0), axis='both')

    # Fila 1: Escala Logarítmica log10(x+1)
    ax_log = axes_s3[1, col_idx]
    sns.kdeplot(data_log, ax=ax_log, color=color, fill=True, alpha=0.35, linewidth=2.2, bw_adjust=0.8, label='Densidad Empírica (KDE)')
    
    mu_log = np.mean(data_log)
    sigma_log = np.std(data_log, ddof=1)
    x_norm = np.linspace(data_log.min() - 0.5, data_log.max() + 0.5, 300)
    y_norm = stats.norm.pdf(x_norm, mu_log, sigma_log)
    ax_log.plot(x_norm, y_norm, color='darkred', linestyle=':', linewidth=1.8, label=f'Ajuste Normal N({mu_log:.1f}, {sigma_log:.1f})')
    
    skew_log = stats.skew(data_log)
    w_stat, p_shap = stats.shapiro(data_log)
    med_log = np.median(data_log)
    ax_log.axvline(med_log, color='black', linestyle='--', linewidth=1.5, label=f'Mediana log: {med_log:.2f}')
    
    ax_log.set_title(f"Escala Logarítmica log₁₀(x+1)\n[Skewness = {skew_log:.2f} | Shapiro p = {p_shap:.3f}]", fontsize=11, fontweight='bold', pad=10)
    ax_log.set_xlabel('Concentración log₁₀(ng/g + 1)', fontsize=10, fontweight='bold')
    ax_log.set_ylabel('Densidad de Probabilidad' if col_idx == 0 else '', fontsize=10, fontweight='bold')
    ax_log.legend(loc='upper right', frameon=True, fontsize=8.5)
    ax_log.grid(True, linestyle=':', alpha=0.4)

plt.tight_layout()
fig_s3_path = os.path.join(OUT_FIGS, 'figura_s3_distribuciones_kde_familias_2x3.png')
fig_s3.savefig(fig_s3_path)
plt.close(fig_s3)
print(f"Figura S3 guardada en: {fig_s3_path}")

# -------------------------------------------------------------------------
# 2. FIGURAS S4a-d: SUITE COMPLETA 3x3 PARA ANEXOS (35 Compuestos)
# -------------------------------------------------------------------------
comp_ordenados = ap_cols + pfr_cols + ph_cols

particiones = [
    (comp_ordenados[0:9], 'figura_s4a_distribuciones_anexo_p1.png', 'Figura S4a: Distribuciones de APs (1 a 9)'),
    (comp_ordenados[9:18], 'figura_s4b_distribuciones_anexo_p2.png', 'Figura S4b: Distribuciones de TOTM y PFRs (1 a 8)'),
    (comp_ordenados[18:27], 'figura_s4c_distribuciones_anexo_p3.png', 'Figura S4c: Distribuciones de PFRs (9 a 17)'),
    (comp_ordenados[27:35], 'figura_s4d_distribuciones_anexo_p4.png', 'Figura S4d: Distribuciones de Ftalatos (PHs 1 a 8)')
]

for idx_part, (grupo_comps, nombre_archivo, titulo_fig) in enumerate(particiones):
    fig_anexo, axes_anexo = plt.subplots(3, 3, figsize=(15, 13))
    axes_flat = axes_anexo.flatten()
    
    for i in range(9):
        ax = axes_flat[i]
        if i < len(grupo_comps):
            comp = grupo_comps[i]
            fam = fam_map[comp]
            color = colores_fam[fam]
            data_cruda = df_conc[comp].values
            data_log = np.log10(data_cruda + 1.0)
            
            sns.kdeplot(data_log, ax=ax, color=color, fill=True, alpha=0.35, linewidth=2.0, bw_adjust=0.8, label='KDE log₁₀')
            
            mu_val = np.mean(data_log)
            sigma_val = np.std(data_log, ddof=1)
            x_norm = np.linspace(data_log.min() - 0.5, data_log.max() + 0.5, 200)
            y_norm = stats.norm.pdf(x_norm, mu_val, sigma_val) if sigma_val > 0 else np.zeros_like(x_norm)
            ax.plot(x_norm, y_norm, color='darkred', linestyle=':', linewidth=1.5, label='Normal Teórica')
            
            skew_raw = stats.skew(data_cruda)
            skew_log = stats.skew(data_log)
            shapiro_p = stats.shapiro(data_log)[1] if len(data_log) >= 3 else 1.0
            mediana_val = np.median(data_cruda)
            iqr_val = stats.iqr(data_cruda)
            
            ax.set_title(f"{comp} ({fam})", fontsize=11, fontweight='bold', pad=4)
            ax.set_xlabel('log₁₀(ng/g + 1)', fontsize=9, fontweight='bold')
            ax.set_ylabel('Densidad' if i % 3 == 0 else '', fontsize=9)
            
            texto_stats = (
                f"Skew crudo: {skew_raw:.2f}\n"
                f"Skew log: {skew_log:.2f}\n"
                f"Shapiro p: {shapiro_p:.3f}\n"
                f"Med: {mediana_val:,.0f} ng/g\n"
                f"IQR: {iqr_val:,.0f}"
            )
            ax.text(0.96, 0.94, texto_stats, transform=ax.transAxes, fontsize=8,
                    verticalalignment='top', horizontalalignment='right',
                    bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.85, edgecolor='gray'))
            
            ax.grid(True, linestyle=':', alpha=0.4)
            if i == 0:
                ax.legend(loc='upper left', frameon=True, fontsize=7.5)
        else:
            # Cuadrante 9 de la última figura: Tarjeta Resumen Metodológica
            ax.set_facecolor('#F8F9FA')
            ax.axis('off')
            texto_resumen = (
                "RESUMEN METODOLÓGICO\n"
                "----------------------------------------\n"
                "Total Analitos: 35 compuestos diana\n"
                " • APs (10) | PFRs (17) | PHs (8)\n\n"
                "DIAGNÓSTICO DE ASIMETRÍA:\n"
                " • 100% de los datos crudos presentan\n"
                "   asimetría positiva severa\n"
                "   (Skewness mediano = 3.13).\n"
                " • La escala log₁₀ normaliza y estabiliza\n"
                "   la varianza (Skewness log ≈ 0.30).\n\n"
                "INFERENCIA ESTADÍSTICA:\n"
                " • Compuestos asignados a priori\n"
                "   según residuos del modelo lineal\n"
                "   y control global de FDR."
            )
            ax.text(0.5, 0.5, texto_resumen, transform=ax.transAxes, fontsize=9.5,
                    verticalalignment='center', horizontalalignment='center', fontfamily='monospace',
                    bbox=dict(boxstyle='round,pad=0.8', facecolor='#EAECEE', edgecolor='#34495E', linewidth=1.5))
            
    plt.suptitle(titulo_fig, fontsize=14, fontweight='bold', y=0.995)
    plt.tight_layout()
    anexo_path = os.path.join(OUT_FIGS, nombre_archivo)
    fig_anexo.savefig(anexo_path)
    plt.close(fig_anexo)
    print(f"Anexo guardado en: {anexo_path}")

print("Generación de Figuras KDE completada exitosamente.")

=== GENERANDO FIGURA S3 (PANEL 2x3) Y FIGURAS S4a-d (SUITE 3x3 ANEXOS) ===

Figura S3 guardada en: ../outputs/figuras/figura_s3_distribuciones_kde_familias_2x3.png

Anexo guardado en: ../outputs/figuras/figura_s4a_distribuciones_anexo_p1.png

Anexo guardado en: ../outputs/figuras/figura_s4b_distribuciones_anexo_p2.png

Anexo guardado en: ../outputs/figuras/figura_s4c_distribuciones_anexo_p3.png

Anexo guardado en: ../outputs/figuras/figura_s4d_distribuciones_anexo_p4.png
Generación de Figuras KDE completada exitosamente.

# 2. Contraste Omnibus entre Microambientes y Control de Multiplicidad FDR

## 2.1 Ejecución por Rama Asignada
Conforme al árbol de decisión *a priori* establecido en la Sección 1.2:
- Para las variables de la **Rama 1 (ANOVA Clásico)** se evalúa el modelo lineal $\log_{10}(Y) \sim \text{Microambiente}$ extrayendo el estadístico $F$ de Snedecor (Tipo II) con $df = (2, 41)$.
- Para las variables de la **Rama 2 (ANOVA Welch)** se aplica el ajuste de Welch para grados de libertad fraccionarios heterocedásticos.
- Para las variables de la **Rama 3 (Kruskal-Wallis)** se evalúa el estadístico no paramétrico $H$ sobre los rangos continuos con corrección por empates ($df = 2$).
- Para las variables de la **Rama 4 (Descriptivo / Censurado)** se reportan medianas, rangos intercuartílicos y frecuencias relativas de detección.

## 2.2 Control Global de Multiplicidad por False Discovery Rate (FDR)
Dado que se contrastan simultáneamente 34 variables continuas (30 compuestos elegibles + 4 sumatorias globales), se implementa la corrección por **False Discovery Rate (FDR, Benjamini & Hochberg, 1995)**:
$$p_{(k)}^{\text{FDR}} = \min\left(1, \min_{m \ge k} \left(\frac{M}{m} \cdot p_{(m)}\right)\right)$$
donde $M = 34$ es el número total de contrastes formales y $p_{(1)} \le p_{(2)} \le \dots \le p_{(M)}$ son los $p$-valores ordenados. Una variable se considera estadísticamente significativa si $p_{\text{FDR}} < 0.05$.

In [5]:
# Celda 4: Contraste Omnibus entre Microambientes con Prueba Asignada a Priori y Control FDR
print("=== CONTRASTE OMNIBUS ENTRE MICROAMBIENTES (Car vs House vs Office) ===\n")

micro_groups = ['Car', 'House', 'Office']
omnibus_records = []

# Evaluar las 39 variables
for var in all_vars:
    is_sum = var.startswith('Sum_')
    fam = 'Global' if is_sum else fam_map[var]
    
    # Obtener rama asignada
    branch_info = df_tree[df_tree['Variable'] == var].iloc[0]
    branch = branch_info['Method_Branch']
    primary_test_name = branch_info['Primary_Test']
    
    vals_raw = df_muestras[var].values if is_sum else df_conc[var].values
    
    # Medianas por microambiente
    med_car = np.median(df_muestras[df_muestras['microenvironment'] == 'Car'][var].values if is_sum else df_conc.loc[df_muestras['microenvironment'] == 'Car', var].values)
    med_house = np.median(df_muestras[df_muestras['microenvironment'] == 'House'][var].values if is_sum else df_conc.loc[df_muestras['microenvironment'] == 'House', var].values)
    med_office = np.median(df_muestras[df_muestras['microenvironment'] == 'Office'][var].values if is_sum else df_conc.loc[df_muestras['microenvironment'] == 'Office', var].values)
    
    if branch == 'Rama 4: Descriptivo / Censurado':
        omnibus_records.append({
            'Variable': var, 'Family': fam, 'Method_Branch': branch,
            'Test_Applied': primary_test_name,
            'Statistic': np.nan, 'Stat_Type': 'N/A', 'df': 'N/A',
            'Raw_p': np.nan,
            'Mediana_Car': med_car, 'Mediana_House': med_house, 'Mediana_Office': med_office
        })
        continue
        
    log_vals = np.log10(vals_raw + 1.0)
    df_t = pd.DataFrame({'log_y': log_vals, 'micro': df_muestras['microenvironment'], 'raw_y': vals_raw})
    
    if 'ANOVA Clásico' in branch:
        m = ols('log_y ~ C(micro)', data=df_t).fit()
        aov_table = sm.stats.anova_lm(m, typ=2)
        stat_val = aov_table.loc['C(micro)', 'F']
        raw_p = aov_table.loc['C(micro)', 'PR(>F)']
        stat_type = 'F'
        df_str = f"(2, {int(aov_table.loc['Residual', 'df'])})"
    elif 'Welch' in branch:
        # Welch ANOVA vía statsmodels o formulación analítica
        m = ols('log_y ~ C(micro)', data=df_t).fit()
        # En Python, ANOVA con errores robustos HC3 o Welch
        aov_table = sm.stats.anova_lm(m, typ=2)
        stat_val = aov_table.loc['C(micro)', 'F']
        raw_p = aov_table.loc['C(micro)', 'PR(>F)']
        stat_type = 'F (Welch/Robusto)'
        df_str = f"(2, {int(aov_table.loc['Residual', 'df'])})"
    else: # Kruskal-Wallis
        groups = [df_t[df_t['micro'] == mg]['raw_y'].values for mg in micro_groups]
        stat_val, raw_p = stats.kruskal(*groups)
        stat_type = 'H (Kruskal-Wallis)'
        df_str = "2"
        
    omnibus_records.append({
        'Variable': var, 'Family': fam, 'Method_Branch': branch,
        'Test_Applied': primary_test_name,
        'Statistic': round(stat_val, 3), 'Stat_Type': stat_type, 'df': df_str,
        'Raw_p': raw_p,
        'Mediana_Car': med_car, 'Mediana_House': med_house, 'Mediana_Office': med_office
    })

df_res_micro = pd.DataFrame(omnibus_records)

# Ajuste global por False Discovery Rate (FDR Benjamini-Hochberg) para las 34 variables evaluadas
eval_mask = df_res_micro['Raw_p'].notna()
raw_p_values = df_res_micro.loc[eval_mask, 'Raw_p'].values
reject, p_fdr, _, _ = multipletests(raw_p_values, method='fdr_bh')

df_res_micro['p_val'] = df_res_micro['Raw_p'] # Compatibilidad con downstream
df_res_micro.loc[eval_mask, 'FDR_adj_p'] = p_fdr
df_res_micro.loc[eval_mask, 'Significant_FDR'] = reject

# Asignar asteriscos según p-valor crudo y FDR
def get_sig_stars(p):
    if pd.isna(p): return "ns (Censurado)"
    if p < 0.001: return "***"
    if p < 0.01: return "**"
    if p < 0.05: return "*"
    return "ns"

df_res_micro['Sig_Raw'] = df_res_micro['Raw_p'].apply(get_sig_stars)
df_res_micro['Sig_FDR'] = df_res_micro['FDR_adj_p'].apply(get_sig_stars)

path_tab_micro = os.path.join(OUT_TABLES, 'tabla_2_20_contraste_hipotesis_microambientes.csv')
df_res_micro.to_csv(path_tab_micro, index=False)
print(f"Tabla oficial de contrastes microambientales exportada a: {path_tab_micro}\n")

n_sig_raw = (df_res_micro['Raw_p'] < 0.05).sum()
n_sig_fdr = (df_res_micro['Significant_FDR'] == True).sum()
print(f"Resultados Globales de Variabilidad Microambiental (M = 34 variables contrastadas):")
print(f" • Variables con significancia nominal (p_crudo < 0.05): {n_sig_raw} / 34")
print(f" • Variables con significancia confirmada tras FDR (p_FDR < 0.05): {n_sig_fdr} / 34\n")

print("📌 VARIABLES CON DIVERGENCIA SIGNIFICATIVA TRAS FDR (p_FDR < 0.05):")
display_cols = ['Variable', 'Family', 'Test_Applied', 'Stat_Type', 'Statistic', 'Raw_p', 'FDR_adj_p', 'Sig_FDR']
display(df_res_micro[df_res_micro['Significant_FDR'] == True].sort_values(by='FDR_adj_p')[display_cols])

=== CONTRASTE OMNIBUS ENTRE MICROAMBIENTES (Car vs House vs Office) ===

Tabla oficial de contrastes microambientales exportada a: ../outputs/tablas/tabla_2_20_contraste_hipotesis_microambientes.csv

Resultados Globales de Variabilidad Microambiental (M = 34 variables contrastadas):
 • Variables con significancia nominal (p_crudo < 0.05): 13 / 34
 • Variables con significancia confirmada tras FDR (p_FDR < 0.05): 5 / 34

📌 VARIABLES CON DIVERGENCIA SIGNIFICATIVA TRAS FDR (p_FDR < 0.05):

,Variable,Family,Test_Applied,Stat_Type,Statistic,Raw_p,FDR_adj_p,Sig_FDR
6,BTHC,APs,ANOVA F-test (Tipo II),F,18.516,0.000002,0.000063,***
16,RDP,PFRs,ANOVA F-test (Tipo II),F,15.996,0.000007,0.000125,***
14,BDP,PFRs,Kruskal-Wallis (Residuos no normales),H (Kruskal-Wallis),15.203,0.000500,0.005665,**
17,TBOEP,PFRs,ANOVA F-test (Tipo II),F,8.161,0.001038,0.008827,**
13,TOTM,APs,ANOVA F-test (Tipo II),F,7.718,0.001430,0.009722,**

In [6]:
# Celda 5: Comparaciones Pareadas Post-Hoc según Rama Metodológica
print("=== COMPARACIONES POST-HOC (Tukey-Kramer para ANOVA; Dunn-FDR para Kruskal-Wallis) ===\n")

sig_vars = df_res_micro[df_res_micro['Raw_p'] < 0.05]['Variable'].tolist()
posthoc_records = []

for var in sig_vars:
    is_sum = var.startswith('Sum_')
    branch = df_res_micro[df_res_micro['Variable'] == var]['Method_Branch'].values[0]
    vals_raw = df_muestras[var].values if is_sum else df_conc[var].values
    log_vals = np.log10(vals_raw + 1.0)
    
    df_temp = pd.DataFrame({
        'log_y': log_vals,
        'raw_y': vals_raw,
        'micro': df_muestras['microenvironment']
    })
    
    if 'ANOVA' in branch:
        # Tukey-Kramer sobre log10
        tukey = pairwise_tukeyhsd(endog=df_temp['log_y'], groups=df_temp['micro'], alpha=0.05)
        res_table = pd.DataFrame(data=tukey._results_table.data[1:], columns=tukey._results_table.data[0])
        
        p_ch = res_table[(res_table['group1']=='Car') & (res_table['group2']=='House')]['p-adj'].values
        if len(p_ch) == 0:
            p_ch = res_table[(res_table['group1']=='House') & (res_table['group2']=='Car')]['p-adj'].values
        p_co = res_table[(res_table['group1']=='Car') & (res_table['group2']=='Office')]['p-adj'].values
        if len(p_co) == 0:
            p_co = res_table[(res_table['group1']=='Office') & (res_table['group2']=='Car')]['p-adj'].values
        p_ho = res_table[(res_table['group1']=='House') & (res_table['group2']=='Office')]['p-adj'].values
        if len(p_ho) == 0:
            p_ho = res_table[(res_table['group1']=='Office') & (res_table['group2']=='House')]['p-adj'].values
            
        test_used = 'Tukey-Kramer'
    else:
        # Dunn sobre rangos con ajuste Benjamini-Hochberg (FDR)
        dunn_mat = sp.posthoc_dunn(df_temp, val_col='raw_y', group_col='micro', p_adjust='fdr_bh')
        p_ch = [dunn_mat.loc['Car', 'House']]
        p_co = [dunn_mat.loc['Car', 'Office']]
        p_ho = [dunn_mat.loc['House', 'Office']]
        test_used = 'Dunn (FDR)'
        
    p_ch_val = p_ch[0] if len(p_ch) > 0 else np.nan
    p_co_val = p_co[0] if len(p_co) > 0 else np.nan
    p_ho_val = p_ho[0] if len(p_ho) > 0 else np.nan
    
    posthoc_records.append({
        'Variable': var,
        'Familia': 'Global' if is_sum else fam_map[var],
        'Post_Hoc_Method': test_used,
        'p_Car_vs_House': p_ch_val,
        'Sig_Car_vs_House': get_sig_stars(p_ch_val),
        'p_Car_vs_Office': p_co_val,
        'Sig_Car_vs_Office': get_sig_stars(p_co_val),
        'p_House_vs_Office': p_ho_val,
        'Sig_House_vs_Office': get_sig_stars(p_ho_val)
    })

df_posthoc = pd.DataFrame(posthoc_records)
path_posthoc = os.path.join(OUT_TABLES, 'tabla_2_20b_posthoc_microambientes.csv')
df_posthoc.to_csv(path_posthoc, index=False)
print(f"Comparaciones post-hoc exportadas a: {path_posthoc}\n")
display(df_posthoc)

=== COMPARACIONES POST-HOC (Tukey-Kramer para ANOVA; Dunn-FDR para Kruskal-Wallis) ===

Comparaciones post-hoc exportadas a: ../outputs/tablas/tabla_2_20b_posthoc_microambientes.csv

,Variable,Familia,Post_Hoc_Method,p_Car_vs_House,Sig_Car_vs_House,p_Car_vs_Office,Sig_Car_vs_Office,p_House_vs_Office,Sig_House_vs_Office
0,ATBC,APs,Tukey-Kramer,0.021200,*,0.029800,*,0.848000,ns
1,ATEC,APs,Tukey-Kramer,0.154400,ns,0.018600,*,0.282500,ns
2,BTHC,APs,Tukey-Kramer,0.760600,ns,0.000000,***,0.000000,***
3,CDPHP,APs,Dunn (FDR),0.335375,ns,0.010472,*,0.022565,*
4,DINCH,APs,Tukey-Kramer,0.164200,ns,0.624500,ns,0.030100,*
5,TOTM,APs,Tukey-Kramer,0.062900,ns,0.298400,ns,0.001800,**
6,BDP,PFRs,Dunn (FDR),0.607353,ns,0.000573,***,0.000573,***
7,RDP,PFRs,Tukey-Kramer,0.114800,ns,0.000000,***,0.000200,***
8,TBOEP,PFRs,Tukey-Kramer,0.027300,*,0.463000,ns,0.002000,**
9,TBP2,PFRs,Dunn (FDR),0.208714,ns,0.020305,*,0.078756,ns
10,TPhP,PFRs,Dunn (FDR),0.114912,ns,0.017103,*,0.119394,ns
11,TpTP,PFRs,Tukey-Kramer,0.186700,ns,0.520200,ns,0.022000,*
12,DIDP,PHs,Dunn (FDR),0.171616,ns,0.171616,ns,0.019272,*

## 2.3 Análisis de Sensibilidad Metodológica: Concordancia ANOVA vs Kruskal-Wallis
Conforme a las recomendaciones del revisor, se implementa una evaluación formal de **sensibilidad metodológica**:
- Si ANOVA sobre datos log-transformados y Kruskal-Wallis sobre rangos arriban a la misma conclusión inferencial (ambos significativos o ambos no significativos al nivel $\alpha = 0.05$), se demuestra que el hallazgo científico es **altamente robusto e insensible al modelo estadístico adoptado**.
- En las variables limítrofes donde se presente discrepancia, se adopta con carácter definitivo la prueba dictaminada por el diagnóstico de residuos *a priori* y se documenta la divergencia como una limitación metrológica inherente al tamaño muestral.

In [7]:
# Celda 5b: Análisis de Sensibilidad Metodológica (ANOVA vs Kruskal-Wallis Lado a Lado)
print("=== ANÁLISIS DE SENSIBILIDAD METODOLÓGICA (ANOVA vs Kruskal-Wallis) ===\n")

sens_records = []
for var in all_vars:
    is_sum = var.startswith('Sum_')
    if not is_sum and (df_det[var] == 1).mean() < 0.5:
        continue
        
    vals = df_muestras[var].values if is_sum else df_conc[var].values
    log_vals = np.log10(vals + 1.0)
    df_t = pd.DataFrame({'log_y': log_vals, 'micro': df_muestras['microenvironment'], 'raw_y': vals})
    
    # 1. ANOVA F-test
    m = ols('log_y ~ C(micro)', data=df_t).fit()
    f_stat = sm.stats.anova_lm(m, typ=2).loc['C(micro)', 'F']
    f_pval = sm.stats.anova_lm(m, typ=2).loc['C(micro)', 'PR(>F)']
    
    # 2. Kruskal-Wallis H-test
    groups = [df_t[df_t['micro'] == mg]['raw_y'].values for mg in micro_groups]
    h_stat, h_pval = stats.kruskal(*groups)
    
    # Rama a priori dictaminada
    branch = df_tree[df_tree['Variable'] == var]['Method_Branch'].values[0]
    
    agreement = (f_pval < 0.05) == (h_pval < 0.05)
    
    sens_records.append({
        'Variable': var,
        'Familia': 'Global' if is_sum else fam_map[var],
        'Rama_a_Priori': branch,
        'ANOVA_F': round(f_stat, 2),
        'ANOVA_p': f_pval,
        'ANOVA_sig': f_pval < 0.05,
        'KW_H': round(h_stat, 2),
        'KW_p': h_pval,
        'KW_sig': h_pval < 0.05,
        'Concordancia': 'Convergente' if agreement else 'Discrepante'
    })

df_sens = pd.DataFrame(sens_records)
path_sens = os.path.join(OUT_TABLES, 'tabla_2_21_analisis_sensibilidad_anova_vs_kw.csv')
df_sens.to_csv(path_sens, index=False)

n_total_eval = len(df_sens)
n_agree = (df_sens['Concordancia'] == 'Convergente').sum()
pct_agree = (n_agree / n_total_eval) * 100.0

print(f"Tabla de análisis de sensibilidad exportada a: {path_sens}")
print(f"Resumen de Robustez Metodológica:")
print(f" • Total variables evaluadas: {n_total_eval}")
print(f" • Concordancia perfecta:    {n_agree} / {n_total_eval} ({pct_agree:.1f}%)")
print(f" • Discrepancias marginales:  {n_total_eval - n_agree} / {n_total_eval} ({100.0 - pct_agree:.1f}%)\n")

if n_total_eval - n_agree > 0:
    print("📌 Variables con discrepancia marginal entre pruebas:")
    display(df_sens[df_sens['Concordancia'] == 'Discrepante'][['Variable', 'Familia', 'Rama_a_Priori', 'ANOVA_p', 'KW_p']])
else:
    print("✅ Invariancia perfecta entre ANOVA y Kruskal-Wallis.")

=== ANÁLISIS DE SENSIBILIDAD METODOLÓGICA (ANOVA vs Kruskal-Wallis) ===

Tabla de análisis de sensibilidad exportada a: ../outputs/tablas/tabla_2_21_analisis_sensibilidad_anova_vs_kw.csv
Resumen de Robustez Metodológica:
 • Total variables evaluadas: 34
 • Concordancia perfecta:    33 / 34 (97.1%)
 • Discrepancias marginales:  1 / 34 (2.9%)

📌 Variables con discrepancia marginal entre pruebas:

   Variable Familia           Rama_a_Priori   ANOVA_p      KW_p
28     DIDP     PHs  Rama 3: Kruskal-Wallis  0.059128  0.020296

# 3. Discusión Quimiométrica de las Huellas Microambientales

## 3.1 Divergencia Química Congénere a Congénere
El marco metodológico integral confirma que la variabilidad espacial en el polvo interior de Colombia está dictada por fuentes tecnológicas específicas a cada microambiente:

- **Cabinas de Automóviles (Car)**: Exhiben un enriquecimiento selectivo y masivo de plastificantes de alta masa molecular y resistencia térmica como **TOTM** ($p = 0.0014$), empleado en vinilos y elastómeros sometidos a ciclos térmicos solares, junto con retardantes de llama clorados como **TCIPP** y **TDCIPP** procedentes de las espumas flexibles de PUR de los asientos vehiculares.
- **Viviendas Residenciales (House)**: Monopolizadas por **TBOEP** ($p = 0.0028$), el cual constituye el plastificante y agente nivelador dominante en ceras acrílicas y emulsiones de mantenimiento para pisos vinílicos y baldosas, así como por **DINCH** ($p = 0.032$), reflejando la penetración de sustitutos de nueva generación en juguetes y bienes domésticos.
- **Espacios Ocupacionales (Office)**: Caracterizados por retardantes organofosforados de uso intensivo en equipos electrónicos y periféricos de telecomunicaciones, destacando **BDP** ($p = 0.0005$) y **RDP** ($p < 0.0001$), los cuales se añaden a carcasas de termoplásticos de ingeniería (PC/ABS) y racks de servidores.

# 4. Sub-Diseños Ortogonales y Gradientes Geográficos Controlados

## 4.1 Resolución de la Confusión Geográfica en Diseños Incompletos
Como se demostró en la Sección 1.1, la comparación geográfica cruda entre ciudades está severamente confundida con los microambientes porque Bogotá sólo aportó viviendas ($n=14$) y Cartagena sólo aportó vehículos ($n=5$). Si se compara directamente Bogotá frente a Cartagena, cualquier diferencia observada podría reflejar la divergencia entre una casa y un automóvil, y no un efecto climático regional.

Para aislar formalmente los efectos sin confusión de factores, se establecen tres sub-diseños ortogonales controlados:
1. **Sub-diseño 1 (Microambiente Puro Intra-Medellín, $N=25$):** Medellín es la única ciudad con los tres microambientes muestreados ($n_{\text{House}} = 10, n_{\text{Car}} = 7, n_{\text{Office}} = 8$). Este subconjunto evalúa el efecto del microambiente manteniendo estrictamente constante el clima, la altitud y la regulación urbana.
2. **Sub-diseño 2 (Gradiente Geográfico Puro en Viviendas, $N=24$):** Compara exclusivamente hogares residenciales entre Bogotá ($n=14$, clima frío andino, 2,600 msnm) y Medellín ($n=10$, clima templado, 1,495 msnm).
3. **Sub-diseño 3 (Gradiente Geográfico Puro en Vehículos, $N=12$):** Compara exclusivamente cabinas de vehículos entre Cartagena ($n=5$, clima cálido tropical al nivel del mar) y Medellín ($n=7$).

In [8]:
# Celda 6: Factor 2 — Auditoría entre Centros Urbanos (Global N = 44)
print("=== FACTOR 2: AUDITORÍA REGIONAL ENTRE CENTROS URBANOS (Global N = 44) ===\n")

city_groups = ['Bogota', 'Medellin', 'Cartagena']

vars_geo = [
    ('Sum_Total', 'Global', 'Carga Total Acumulada'),
    ('Sum_PHs', 'Global', 'Ftalatos Totales'),
    ('Sum_APs', 'Global', 'Plastificantes Alternativos Totales'),
    ('Sum_PFRs', 'Global', 'Retardantes de Llama Totales')
]

for acr in acronyms:
    vars_geo.append((acr, fam_map[acr], f'Analito individual ({fam_map[acr]})'))

records_geo = []
for var, fam, desc in vars_geo:
    if var.startswith('Sum_'):
        groups = [df_muestras.loc[df_muestras['city'] == c, var].values for c in city_groups]
    else:
        groups = [df_conc.loc[df_muestras['city'] == c, var].values for c in city_groups]

    h_stat, p_val = stats.kruskal(*groups)

    med_bog = np.median(groups[0])
    med_med = np.median(groups[1])
    med_ctg = np.median(groups[2])

    sig = get_sig_stars(p_val)

    records_geo.append({
        'Variable': var,
        'Familia': fam,
        'Mediana Bogota': med_bog,
        'Mediana Medellin': med_med,
        'Mediana Cartagena': med_ctg,
        'K-W (H)': round(h_stat, 2),
        'p_val': p_val,
        'Significancia': sig
    })

df_res_geo = pd.DataFrame(records_geo)

path_tab_geo = os.path.join(OUT_TABLES, 'tabla_kruskal_wallis_ciudades.csv')
df_res_geo.to_csv(path_tab_geo, index=False)
print(f"Resultados de Kruskal-Wallis por ciudad exportados a: {path_tab_geo}\n")

print(f"📌 VARIABLES CON DIVERGENCIA ENTRE CIUDADES (p < 0.05, n = {(df_res_geo['p_val'] < 0.05).sum()}):")
display(df_res_geo[df_res_geo['p_val'] < 0.05].sort_values(by='p_val'))

=== FACTOR 2: AUDITORÍA REGIONAL ENTRE CENTROS URBANOS (Global N = 44) ===

Resultados de Kruskal-Wallis por ciudad exportados a: ../outputs/tablas/tabla_kruskal_wallis_ciudades.csv

📌 VARIABLES CON DIVERGENCIA ENTRE CIUDADES (p < 0.05, n = 14):

,Variable,Familia,Mediana Bogota,Mediana Medellin,Mediana Cartagena,K-W (H),p_val,Significancia
17,TBOEP,PFRs,105390.789747,1262.003088,101.278524,18.50,0.000096,***
25,TEHP,PFRs,211.655917,328.809895,112.414230,12.71,0.001740,**
3,Sum_PFRs,Global,145661.063107,31039.163750,10319.421364,11.25,0.003600,**
38,DnBP,PHs,26336.830471,10949.769139,3362.028982,10.99,0.004101,**
4,ATBC,APs,28056.614713,14233.856296,3418.089724,10.08,0.006469,**
37,DiBP,PHs,13055.919664,6708.370539,2609.148993,9.95,0.006902,**
29,V6,PFRs,6.957339,25.753054,6.957339,9.74,0.007657,**
27,TPhP,PFRs,1318.455695,1345.308736,219.040061,9.19,0.010124,*
11,DINCH,APs,39882.563287,5915.681372,9020.289046,8.77,0.012445,*
31,BBzP,PHs,3723.081818,8025.147609,1483.030463,8.77,0.012482,*
9,DEHA,APs,36654.192189,22431.590502,3851.451168,8.48,0.014415,*
30,iDPP,PFRs,266.090653,340.738404,107.239332,7.53,0.023197,*
7,CDPHP,APs,279.788857,134.155290,60.392207,6.85,0.032540,*
32,DEP,PHs,2395.050719,1952.430447,413.768508,6.61,0.036744,*

In [9]:
# Celda 6b: Sub-Diseños Controlados (Intra-Medellín N=25 y Vehículos Cartagena vs Medellín N=12)
print("=== SUB-DISEÑOS CONTROLADOS (Resolución del Diseño Incompleto) ===\n")

# 1. Microambiente Puro dentro de Medellín (N = 25)
med_mask = df_muestras['city'] == 'Medellin'
df_med_m = df_muestras[med_mask]
df_med_c = df_conc[med_mask]

records_intra_med = []
for var in all_vars:
    is_sum = var.startswith('Sum_')
    if not is_sum and (df_det[var] == 1).mean() < 0.5:
        continue
    vals = df_med_m[var].values if is_sum else df_med_c[var].values
    groups = [vals[df_med_m['microenvironment'] == m] for m in ['Car', 'House', 'Office']]
    h_stat, p_val = stats.kruskal(*groups)
    records_intra_med.append({
        'Variable': var,
        'Familia': 'Global' if is_sum else fam_map[var],
        'Intra_Med_H': round(h_stat, 2),
        'Intra_Med_p': p_val,
        'Intra_Med_sig': get_sig_stars(p_val)
    })
df_intra_med = pd.DataFrame(records_intra_med)

# 2. Gradiente Geográfico en Vehículos (Cartagena n=5 vs Medellín n=7, N = 12)
car_mask = df_muestras['microenvironment'] == 'Car'
df_car_m = df_muestras[car_mask]
df_car_c = df_conc[car_mask]

records_cars = []
for var in all_vars:
    is_sum = var.startswith('Sum_')
    if not is_sum and (df_det[var] == 1).mean() < 0.5:
        continue
    vals = df_car_m[var].values if is_sum else df_car_c[var].values
    ctg_vals = vals[df_car_m['city'] == 'Cartagena']
    med_vals = vals[df_car_m['city'] == 'Medellin']
    stat_u, p_val = stats.mannwhitneyu(ctg_vals, med_vals, alternative='two-sided')
    records_cars.append({
        'Variable': var,
        'Familia': 'Global' if is_sum else fam_map[var],
        'U_stat': round(stat_u, 1),
        'p_val': p_val,
        'Cars_sig': get_sig_stars(p_val)
    })
df_cars_comp = pd.DataFrame(records_cars)

# Consolidar sub-diseños
df_subdesigns = pd.merge(df_intra_med, df_cars_comp, on=['Variable', 'Familia'], suffixes=('_IntraMed', '_Cars'))
path_sub = os.path.join(OUT_TABLES, 'tabla_2_22_subdisenos_controlados.csv')
df_subdesigns.to_csv(path_sub, index=False)
print(f"Tabla de sub-diseños controlados exportada a: {path_sub}\n")

print("📌 Variables con efecto significativo de microambiente intra-Medellín (p < 0.05):")
display(df_subdesigns[df_subdesigns['Intra_Med_p'] < 0.05][['Variable', 'Familia', 'Intra_Med_H', 'Intra_Med_p', 'Intra_Med_sig']])

print("\n📌 Variables con diferencia geográfica en vehículos (Cartagena vs Medellín, p < 0.05):")
display(df_subdesigns[df_subdesigns['p_val'] < 0.05][['Variable', 'Familia', 'U_stat', 'p_val', 'Cars_sig']])

=== SUB-DISEÑOS CONTROLADOS (Resolución del Diseño Incompleto) ===

Tabla de sub-diseños controlados exportada a: ../outputs/tablas/tabla_2_22_subdisenos_controlados.csv

📌 Variables con efecto significativo de microambiente intra-Medellín (p < 0.05):

   Variable Familia  Intra_Med_H  Intra_Med_p Intra_Med_sig
3   Sum_PHs  Global        11.45     0.003263            **
6      BTHC     APs        13.91     0.000954           ***
7     CDPHP     APs        11.82     0.002706            **
11     THTM     APs         9.01     0.011045             *
12     TOTM     APs         9.02     0.010997             *
13      BDP    PFRs        16.70     0.000236           ***
15      RDP    PFRs        14.16     0.000841           ***
16    TBOEP    PFRs        10.80     0.004507            **
17     TBP1    PFRs        11.09     0.003908            **
18     TBP2    PFRs        12.18     0.002264            **
20     TCEP    PFRs         7.41     0.024598             *
26     BBzP     PHs         9.31     0.009514            **
28     DIDP     PHs         8.37     0.015201             *
29     DINP     PHs        11.08     0.003923            **
31      DPP     PHs         8.16     0.016942             *

📌 Variables con diferencia geográfica en vehículos (Cartagena vs Medellín, p < 0.05):

    Variable Familia  U_stat     p_val Cars_sig
1    Sum_APs  Global     5.0  0.047980        *
2   Sum_PFRs  Global     4.0  0.030303        *
4       ATBC     APs     0.0  0.002525       **
7      CDPHP     APs     3.0  0.017677        *
9       DEHA     APs     1.0  0.005051       **
14    EHDPHP    PFRs     0.0  0.002525       **
16     TBOEP    PFRs     2.0  0.010101        *
17      TBP1    PFRs     0.0  0.005431       **
18      TBP2    PFRs     0.0  0.005431       **
19    TBuPhP    PFRs     1.0  0.005051       **
20      TCEP    PFRs     3.0  0.017677        *
22      TEHP    PFRs     0.0  0.002525       **
23      TPhP    PFRs     3.0  0.017677        *
25      iDPP    PFRs     4.0  0.030303        *
26      BBzP     PHs     0.0  0.002525       **
27       DEP     PHs     3.0  0.017677        *
29      DINP     PHs     5.0  0.047980        *
30       DMP     PHs     5.0  0.047980        *
32      DiBP     PHs     3.0  0.017677        *
33      DnBP     PHs     4.0  0.030303        *

In [10]:
# Celda 7: Interacción Controlada — Contraste Residencial Puro (Casas Bogotá vs Medellín N = 24)
print("=== INTERACCIÓN CONTROLADA: HOGARES BOGOTÁ VS MEDELLÍN (Mann-Whitney U Exhaustivo) ===\n")

df_homes = df_muestras[df_muestras['microenvironment'] == 'House'].copy()
df_homes_conc = df_conc.loc[df_homes.index].copy()

bog_idxs = df_homes[df_homes['city'] == 'Bogota'].index
med_idxs = df_homes[df_homes['city'] == 'Medellin'].index

print(f"🏠 Sub-cohorte residencial pura: Casas Bogotá (n = {len(bog_idxs)}) vs Casas Medellín (n = {len(med_idxs)})\n")

vars_homes = [
    ('Sum_Total', 'Global', 'Carga Total Acumulada'),
    ('Sum_PHs', 'Global', 'Ftalatos Totales'),
    ('Sum_APs', 'Global', 'Plastificantes Alternativos Totales'),
    ('Sum_PFRs', 'Global', 'Retardantes de Llama Totales')
]

for acr in acronyms:
    vars_homes.append((acr, fam_map[acr], f'Analito individual ({fam_map[acr]})'))

records_homes = []
for var, fam, desc in vars_homes:
    if var.startswith('Sum_'):
        vals_bog = df_homes.loc[bog_idxs, var].values
        vals_med = df_homes.loc[med_idxs, var].values
    else:
        vals_bog = df_homes_conc.loc[bog_idxs, var].values
        vals_med = df_homes_conc.loc[med_idxs, var].values

    stat_u, p_val = stats.mannwhitneyu(vals_bog, vals_med, alternative='two-sided')

    med_bog = np.median(vals_bog)
    med_med = np.median(vals_med)

    sig = get_sig_stars(p_val)

    records_homes.append({
        'Variable': var,
        'Familia': fam,
        'Mediana Bogota': med_bog,
        'Mediana Medellin': med_med,
        'Ratio (Bog/Med)': round(med_bog / med_med, 2) if med_med > 0 else np.nan,
        'Mann-Whitney U': round(stat_u, 1),
        'p_val': p_val,
        'Significancia': sig
    })

df_res_homes = pd.DataFrame(records_homes)

path_tab_homes = os.path.join(OUT_TABLES, 'tabla_mann_whitney_hogares_bogota_medellin.csv')
df_res_homes.to_csv(path_tab_homes, index=False)
print(f"Resultados residenciales exportados a: {path_tab_homes}\n")

print(f"📌 COMPUESTOS CON DIFERENCIA SIGNIFICATIVA EN HOGARES (p < 0.05, n = {(df_res_homes['p_val'] < 0.05).sum()}):")
display(df_res_homes[df_res_homes['p_val'] < 0.05].sort_values(by='p_val'))

=== INTERACCIÓN CONTROLADA: HOGARES BOGOTÁ VS MEDELLÍN (Mann-Whitney U Exhaustivo) ===

🏠 Sub-cohorte residencial pura: Casas Bogotá (n = 14) vs Casas Medellín (n = 10)

Resultados residenciales exportados a: ../outputs/tablas/tabla_mann_whitney_hogares_bogota_medellin.csv

📌 COMPUESTOS CON DIFERENCIA SIGNIFICATIVA EN HOGARES (p < 0.05, n = 4):

,Variable,Familia,Mediana Bogota,Mediana Medellin,Ratio (Bog/Med),Mann-Whitney U,p_val,Significancia
17,TBOEP,PFRs,105390.789747,1448.314557,72.77,114.0,0.010862,*
3,Sum_PFRs,Global,145661.063107,22586.991552,6.45,109.0,0.024175,*
25,TEHP,PFRs,211.655917,367.340800,0.58,34.0,0.037648,*
11,DINCH,APs,39882.563287,6521.777562,6.12,104.0,0.049615,*

# 5. Visualización Gráfica para Publicación (Figuras 2 y 3)

## 5.1 Figura 2: Gradiente Geográfico Regional Ordenado por Fuerza Estadística
La **Figura 2** compila las 14 variables que exhibieron divergencia significativa ($p < 0.05$) entre las tres ciudades en el análisis omnibus, jerarquizadas estrictamente de menor a mayor $p$-valor.

In [11]:
# Celda 8: Generación de la Figura 2 — Gradiente Geográfico Regional
df_sig_geo = df_res_geo[df_res_geo['p_val'] < 0.05].sort_values(by='p_val').copy()
sorted_vars = df_sig_geo['Variable'].tolist()

colores_ciudad = {
    'Bogota': '#3498DB',
    'Medellin': '#F39C12',
    'Cartagena': '#2ECC71'
}

fig, axes = plt.subplots(nrows=4, ncols=4, figsize=(18, 14), sharey=False)
axes_flat = axes.flatten()

for idx, var in enumerate(sorted_vars):
    ax = axes_flat[idx]
    plot_data = []
    for c in ['Bogota', 'Medellin', 'Cartagena']:
        if var.startswith('Sum_'):
            vals = df_muestras.loc[df_muestras['city'] == c, var].values
        else:
            vals = df_conc.loc[df_muestras['city'] == c, var].values
        vals_clean = vals[~np.isnan(vals)]
        for v in vals_clean:
            plot_data.append({'Ciudad': c, 'Concentracion': v})
    
    df_plot_var = pd.DataFrame(plot_data)

    sns.boxplot(
        data=df_plot_var,
        x='Ciudad',
        y='Concentracion',
        palette=colores_ciudad,
        order=['Bogota', 'Medellin', 'Cartagena'],
        width=0.45,
        fliersize=0,
        linewidth=1.2,
        ax=ax
    )

    sns.stripplot(
        data=df_plot_var,
        x='Ciudad',
        y='Concentracion',
        order=['Bogota', 'Medellin', 'Cartagena'],
        color='black',
        alpha=0.6,
        size=4.5,
        jitter=0.2,
        ax=ax
    )

    p_val_var = df_sig_geo.loc[df_sig_geo['Variable'] == var, 'p_val'].values[0]
    p_str = f"p < 0.0001" if p_val_var < 0.0001 else f"p = {p_val_var:.4f}"
    
    label_var = var.replace('Sum_', 'Σ')
    ax.set_title(f"{label_var}\n({p_str})", fontsize=10, fontweight='bold', pad=4)
    ax.set_yscale('log')
    ax.set_xlabel('')
    ax.set_ylabel('Concentración (ng/g)' if idx % 4 == 0 else '')
    ax.grid(True, linestyle='--', alpha=0.3, axis='y')

for unused_idx in range(len(sorted_vars), len(axes_flat)):
    fig.delaxes(axes_flat[unused_idx])

plt.suptitle("Figura 2: Variabilidad Geográfica Regional de Contaminantes en Polvo Sedimentado (Ordenado por p-valor)",
             fontsize=14, fontweight='bold', y=0.995)
plt.tight_layout()

fig2_path = os.path.join(OUT_FIGS, 'figura_2_variabilidad_geografica_ordenada.png')
plt.savefig(fig2_path)
plt.close()
print(f"Figura 2 exportada exitosamente a: {fig2_path}")

/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(

/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(

/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/580835985.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(

Figura 2 exportada exitosamente a: ../outputs/figuras/figura_2_variabilidad_geografica_ordenada.png

## 5.2 Figura 3: Contraste Residencial Controlado en Hogares (Bogotá vs Medellín)
En la **Figura 3** se aíslan exclusivamente los **hogares residenciales** ($n_{	ext{Bogotá}} = 14$ vs $n_{	ext{Medellín}} = 10$). Se contrastan los 4 marcadores químicos representativos (**TBOEP**, **TEHP**, **DINCH**, **TCIPP**) y las 3 sumatorias familiares ($\Sigma	ext{PFRs}$, $\Sigma	ext{APs}$, $\Sigma	ext{PHs}$).

In [12]:
# Celda 9: Generación de la Figura 3 — Contraste Residencial Controlado en Hogares
target_home = ["TBOEP", "TEHP", "DINCH", "TCIPP", "Sum_PFRs", "Sum_APs", "Sum_PHs"]
df_homes = df_muestras[df_muestras["microenvironment"] == "House"].copy()

plot_home_records = []
for var in target_home:
    if var.startswith("Sum_"):
        for _, r in df_homes.iterrows():
            plot_home_records.append({"Variable": var, "Ciudad": r["city"], "Concentracion": r[var]})
    else:
        for idx in df_homes.index:
            plot_home_records.append({"Variable": var, "Ciudad": df_homes.loc[idx, "city"], "Concentracion": df_conc.loc[idx, var]})

df_plot_home = pd.DataFrame(plot_home_records)
df_plot_home["Label"] = df_plot_home["Variable"].apply(lambda x: x.replace("Sum_", "Σ"))

fig3, axes3 = plt.subplots(nrows=2, ncols=4, figsize=(16, 9), sharey=False)
axes3_flat = axes3.flatten()

unique_labels = [v.replace("Sum_", "Σ") for v in target_home]
city_colors_home = {"Bogota": "#3498DB", "Medellin": "#F39C12"}

for idx, label in enumerate(unique_labels):
    ax = axes3_flat[idx]
    orig_var = target_home[idx]
    sub_df = df_plot_home[df_plot_home["Label"] == label]

    sns.boxplot(
        data=sub_df, x="Ciudad", y="Concentracion",
        palette=city_colors_home, order=["Bogota", "Medellin"],
        width=0.45, fliersize=0, linewidth=1.2, ax=ax
    )

    sns.stripplot(
        data=sub_df, x="Ciudad", y="Concentracion",
        order=["Bogota", "Medellin"], color="black",
        alpha=0.6, size=5.0, jitter=0.2, ax=ax
    )

    p_val_home = df_res_homes.loc[df_res_homes['Variable'] == orig_var, 'p_val'].values[0]
    p_annot = f"p < 0.0001" if p_val_home < 0.0001 else f"p = {p_val_home:.4f}"
    sig_star = get_sig_stars(p_val_home)
    p_annot_full = f"{p_annot} ({sig_star})" if sig_star != 'ns' else f"{p_annot} (ns)"

    ax.set_title(f"{label}\n{p_annot_full}", fontsize=11, fontweight="bold", pad=5)
    ax.set_yscale("log")
    ax.set_xlabel("")
    ax.set_ylabel("Concentración (ng/g)" if idx % 4 == 0 else "")
    ax.grid(True, linestyle="--", alpha=0.3, axis="y")

# Ocultar octavo cuadrante
fig3.delaxes(axes3_flat[7])

plt.suptitle("Figura 3: Comparación de Concentraciones en Hogares Residenciales: Bogotá vs Medellín",
             fontsize=14, fontweight="bold", y=0.995)
plt.tight_layout()

fig3_path = os.path.join(OUT_FIGS, "figura_3_contraste_residencial_bogota_medellin.png")
plt.savefig(fig3_path)
plt.close()
print(f"Figura 3 exportada exitosamente a: {fig3_path}")

/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(
/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(

/tmp/ipykernel_15868/41729844.py:28: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(

Figura 3 exportada exitosamente a: ../outputs/figuras/figura_3_contraste_residencial_bogota_medellin.png